// export default {
//   panels: [
//     {
//       index: 0,
//       height: 297,
//       width: 210,
//       paperHeader: 49.5,
//       paperFooter: 780,
//       printElements: [
//         {
//           options: {
//             left: 175.5,
//             top: 10.5,
//             height: 27,
//             width: 259,
//             title: "HiPrint自定义模块打印插件",
//             fontSize: 19,
//             fontWeight: "600",
//             textAlign: "center",
//             lineHeight: 26,
//             coordinateSync: true,
//             widthHeightSync: true,
//             draggable: false,
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 60, top: 27, height: 13, width: 52, title: "页眉线", textAlign: "center" },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 25.5, top: 57, height: 705, width: 9, fixed: true, borderStyle: "dotted" },
//           printElementType: { type: "vline" },
//         },
//         {
//           options: { left: 60, top: 61.5, height: 48, width: 87, src: "", fit: "contain" },
//           printElementType: { title: "图片", type: "image" },
//         },
//         {
//           options: {
//             left: 153,
//             top: 64.5,
//             height: 39,
//             width: 276,
//             title: "二维码以及条形码均采用svg格式打印。不同打印机打印不会造成失真。图片打印：不同DPI打印可能会导致失真，",
//             fontFamily: "微软雅黑",
//             textAlign: "center",
//             lineHeight: 18,
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 457.5,
//             top: 79.5,
//             height: 13,
//             width: 120,
//             title: "姓名",
//             field: "name",
//             testData: "古力娜扎",
//             color: "#f00808",
//             textDecoration: "underline",
//             textAlign: "center",
//             fields: [
//               { text: "id", field: "id" },
//               { text: "姓名", field: "name" },
//               { text: "性别", field: "gender" },
//               { text: "数量", field: "count" },
//             ],
//           },
//           printElementType: { title: "文本", type: "text" },
//         },
//         {
//           options: {
//             left: 483,
//             top: 124.5,
//             height: 43,
//             width: 51,
//             title: "123456789",
//             textType: "qrcode",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 285,
//             top: 130.5,
//             height: 34,
//             width: 175,
//             title: "123456789",
//             fontFamily: "微软雅黑",
//             textAlign: "center",
//             textType: "barcode",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 60,
//             top: 132,
//             height: 19,
//             width: 213,
//             title: "所有打印元素都可已拖拽的方式来改变元素大小",
//             fontFamily: "微软雅黑",
//             textAlign: "center",
//             lineHeight: 18,
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 153,
//             top: 189,
//             height: 13,
//             width: 238,
//             title: "单击元素，右侧可自定义元素属性",
//             textAlign: "center",
//             fontFamily: "微软雅黑",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 60, top: 190.5, height: 13, width: 51, title: "横线", textAlign: "center" },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 415.5,
//             top: 190.5,
//             height: 13,
//             width: 164,
//             title: "可以配置各属性的默认值",
//             textAlign: "center",
//             fontFamily: "微软雅黑",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 60, top: 214.5, height: 10, width: 475.5 },
//           printElementType: { title: "横线", type: "hline" },
//         },
//         {
//           options: {
//             left: 235.5,
//             top: 220.5,
//             height: 32,
//             width: 342,
//             title: "自定义表格：用户可左键选中表头，右键查看可操作项，操作类似Excel，双击表头单元格可进行编辑。内容：title#field",
//             fontFamily: "微软雅黑",
//             textAlign: "center",
//             lineHeight: 15,
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 156,
//             top: 265.5,
//             height: 13,
//             width: 94,
//             title: "表头列大小可拖动",
//             fontFamily: "微软雅黑",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 60,
//             top: 265.5,
//             height: 13,
//             width: 90,
//             title: "红色区域可拖动",
//             fontFamily: "微软雅黑",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 60,
//             top: 285,
//             height: 56,
//             width: 511.5,
//             field: "table",
//             tableFooterRepeat: "",
//             fields: [
//               { text: "id", field: "id" },
//               { text: "姓名", field: "name" },
//               { text: "性别", field: "gender" },
//               { text: "数量", field: "count" },
//             ],
//             columns: [
//               [
//                 { width: 85.25, colspan: 1, rowspan: 1, checked: true },
//                 {
//                   title: "性别",
//                   field: "gender",
//                   width: 85.25,
//                   colspan: 1,
//                   rowspan: 1,
//                   checked: false,
//                 },
//                 {
//                   title: "姓名",
//                   field: "name",
//                   width: 85.25,
//                   align: "center",
//                   colspan: 1,
//                   rowspan: 1,
//                   checked: true,
//                   tableSummary: "count",
//                 },
//                 {
//                   title: "数量",
//                   field: "count",
//                   width: 85.25,
//                   align: "center",
//                   colspan: 1,
//                   rowspan: 1,
//                   checked: true,
//                   tableSummary: "sum",
//                 },
//                 {
//                   width: 85.25,
//                   colspan: 1,
//                   rowspan: 1,
//                   checked: true,
//                 },
//                 { width: 85.25, colspan: 1, rowspan: 1, checked: true },
//               ],
//             ],
//           },
//           printElementType: {
//             title: "表格",
//             type: "table",
//           },
//         },
//         {
//           options: {
//             left: 21,
//             top: 346.5,
//             height: 61.5,
//             width: 15,
//             title: "装订线",
//             lineHeight: 18,
//             fixed: true,
//             contentPaddingTop: 3.75,
//             backgroundColor: "#ffffff",
//           },
//           printElementType: { type: "text" },
//         },
//         {
//           options: {
//             left: 225,
//             top: 355,
//             height: 13,
//             width: 346.5,
//             title: "自定义模块：主要为开发人员设计，能够快速，简单，实现自己功能",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 60, top: 370.5, height: 18, width: 79, title: "配置项表格", textAlign: "center" },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 225,
//             top: 385.5,
//             height: 38,
//             width: 346.5,
//             title: "配置模块：主要为客户使用，开发人员可以配置属性，字段，标题等，客户直接使用，配置模块请参考实例2",
//             fontFamily: "微软雅黑",
//             lineHeight: 15,
//             textAlign: "center",
//             color: "#d93838",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 60,
//             top: 487.5,
//             height: 13,
//             width: 123,
//             title: "长文本会自动分页",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 60, top: 507, height: 40, width: 511.5, field: "longText" },
//           printElementType: { title: "长文", type: "longText" },
//         },
//         {
//           options: { left: 475.5, top: 565.5, height: 100, width: 100 },
//           printElementType: { title: "矩形", type: "rect" },
//         },
//         {
//           options: { left: 174, top: 568.5, height: 13, width: 90, title: "竖线", textAlign: "center" },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 60, top: 574.5, height: 100, width: 10 },
//           printElementType: { title: "竖线", type: "vline" },
//         },
//         {
//           options: { left: 210, top: 604.5, height: 13, width: 120, title: "横线", textAlign: "center" },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 130.5, top: 625.5, height: 10, width: 277 },
//           printElementType: { title: "横线", type: "hline" },
//         },
//         {
//           options: {
//             left: 364.5,
//             top: 649.5,
//             height: 13,
//             width: 101,
//             title: "矩形",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 525, top: 784.5, height: 13, width: 63, title: "页尾线", textAlign: "center" },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: { left: 12, top: 786, height: 49, width: 49 },
//           printElementType: { title: "html", type: "html" },
//         },
//         {
//           options: {
//             left: 75,
//             top: 790.5,
//             height: 13,
//             width: 137,
//             title: "红色原型是自动定义的Html",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//         {
//           options: {
//             left: 334.5,
//             top: 810,
//             height: 13,
//             width: 205,
//             title: "页眉线已上。页尾下以下每页都会重复打印",
//             textAlign: "center",
//           },
//           printElementType: { title: "自定义文本", type: "text" },
//         },
//       ],
//       paperNumberLeft: 565.5,
//       paperNumberTop: 819,
//     },
//   ],
// };

export default {
  panels: [
    {
      index: 0,
      name: 1,
      paperType: "A4",
      height: 297,
      width: 210,
      paperHeader: 0,
      paperFooter: 841.8897637795277,
      printElements: [
        {
          options: {
            left: 225,
            top: 10.5,
            height: 17,
            width: 120,
            testData: "单据表头",
            fontSize: 16.5,
            fontWeight: "500",
            textAlign: "center",
            hideTitle: true,
            title: "销售出库单",
            right: 334.5,
            bottom: 37.25,
            vCenter: 274.5,
            hCenter: 28.75,
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
          },
          printElementType: {
            title: "单据表头",
            type: "text",
          },
        },
        {
          options: {
            left: 456,
            top: 16.5,
            height: 9.75,
            width: 120,
            title: "销售日期",
            right: 572.25,
            bottom: 36.75,
            vCenter: 512.25,
            hCenter: 31.875,
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            field: "busDate",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 21,
            top: 43.5,
            height: 9.75,
            width: 120,
            title: "仓库",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            field: "name",
            testData: "xx总仓",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 225,
            top: 45,
            height: 9.75,
            width: 120,
            title: "客户",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            right: 344.25,
            bottom: 65.25,
            vCenter: 284.25,
            hCenter: 60.375,
            field: "customerId",
            testData: "里斯",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 400.5,
            top: 46.5,
            height: 9.75,
            width: 175.5,
            title: "单据编号",
            right: 574.5,
            bottom: 66.75,
            vCenter: 486.75,
            hCenter: 61.875,
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            field: "code",
            testData: "111",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 225,
            top: 70.5,
            height: 9.75,
            width: 328.5,
            title: "地址",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            field: "address",
            testData: "巴中恩阳高映林",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 19.5,
            top: 72,
            height: 9.75,
            width: 120,
            title: "客户电话",
            right: 137.25,
            bottom: 91.5,
            vCenter: 77.25,
            hCenter: 86.625,
            field: "phone",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            testData: "13880000000",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 19.5,
            top: 100.5,
            height: 66,
            width: 556.5,
            field: "table",
            footerFormatter:
              'function (options, rows, data, currentPageGridRowsData) {\n        console.log(currentPageGridRowsData);\n        if (data && data["totalCap"]) {\n          return `<td style="padding:0 10px" colspan="100">${"合计: " + data["totalCap"]}</td>`;\n        }\n        return \'<td style="padding:0 10px" colspan="100">合计: </td>\';\n      }',
            right: 573.75,
            bottom: 177,
            vCenter: 295.5,
            hCenter: 144,
            tableFooterRepeat: "page",
            coordinateSync: false,
            widthHeightSync: false,
            tableHeaderRepeat: "page",
            columns: [
              [
                {
                  width: 79.5,
                  title: "商   品   名   称",
                  field: "materialIdTxt",
                  checked: true,
                  columnId: "materialIdTxt",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 79.16485714285714,
                  title: "单位",
                  field: "unit",
                  checked: true,
                  columnId: "unit",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 79.83514285714286,
                  title: "规格",
                  field: "specification",
                  checked: true,
                  columnId: "specification",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                },
                {
                  width: 79.5,
                  title: "数量",
                  field: "totalQuantity",
                  checked: true,
                  columnId: "totalQuantity",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                },
                {
                  width: 79.5,
                  title: "单价（元）",
                  field: "price",
                  checked: true,
                  columnId: "price",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                  tableQRCodeLevel: 0,
                  tableSummaryTitle: true,
                  tableSummary: "",
                },
                {
                  width: 79.5,
                  title: "金额",
                  field: "totalAmount",
                  checked: true,
                  columnId: "totalAmount",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                },
                {
                  width: 79.5,
                  title: "备注",
                  field: "remark",
                  checked: true,
                  columnId: "remark",
                  fixed: false,
                  rowspan: 1,
                  colspan: 1,
                  align: "center",
                },
              ],
            ],
          },
          printElementType: {
            title: "订单数据",
            type: "table",
            editable: true,
            columnDisplayEditable: true,
            columnDisplayIndexEditable: true,
            columnTitleEditable: true,
            columnResizable: true,
            columnAlignEditable: true,
            isEnableEditField: true,
            isEnableContextMenu: true,
            isEnableInsertRow: true,
            isEnableDeleteRow: true,
            isEnableInsertColumn: true,
            isEnableDeleteColumn: true,
            isEnableMergeCell: true,
          },
        },
        {
          options: {
            left: 400.5,
            top: 181.5,
            height: 9.75,
            width: 175.5,
            title: "客户签字：",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            right: 560.25,
            bottom: 201,
            vCenter: 479.25,
            hCenter: 196.125,
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 19.5,
            top: 183,
            height: 9.75,
            width: 120,
            title: "制单",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            field: "uy",
            testData: "熊星玉",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 223.5,
            top: 183,
            height: 9.75,
            width: 120,
            title: "经手人",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            field: "qq",
            testData: "董xx",
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 19.5,
            top: 207,
            height: 9.75,
            width: 249,
            title: "地址：四川省xx市xx区xx1号附31号    ",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
        {
          options: {
            left: 400.5,
            top: 207,
            height: 9.75,
            width: 175.5,
            title: "联系电话：",
            coordinateSync: false,
            widthHeightSync: false,
            qrCodeLevel: 0,
            right: 552.75,
            bottom: 226.5,
            vCenter: 490.5,
            hCenter: 221.625,
          },
          printElementType: {
            title: "文本",
            type: "text",
          },
        },
      ],
      paperNumberLeft: 565,
      paperNumberTop: 573,
      paperNumberDisabled: true,
      watermarkOptions: {
        content: "",
        fillStyle: "rgba(184, 184, 184, 0.3)",
        fontSize: "14px",
        rotate: 25,
        width: 800,
        height: 100,
        timestamp: false,
        format: "YYYY-MM-DD HH:mm",
      },
    },
  ],
};
